# Generated by Django 2.0.8 on 2018-10-17 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_products'),
    ]

    operations = [
        migrations.DeleteModel(
            name='products',
        ),
    ]
