# Generated by Django 2.0.8 on 2018-10-17 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_product'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='product',
            new_name='products',
        ),
    ]
