# Generated by Django 2.0.8 on 2018-10-17 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20181017_1803'),
    ]

    operations = [
        migrations.DeleteModel(
            name='product',
        ),
    ]
