# Generated by Django 2.0.8 on 2018-10-17 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0003_delete_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_category', models.IntegerField()),
                ('product_sub_category', models.IntegerField()),
                ('product_name', models.CharField(max_length=255)),
                ('product_short_description', models.CharField(max_length=255)),
                ('product_SKU', models.CharField(max_length=100)),
                ('product_full_description', models.CharField(max_length=100)),
                ('product_additional_info', models.CharField(max_length=100)),
                ('product_image', models.CharField(max_length=255)),
            ],
        ),
    ]
